# Generated by Django 5.0.6 on 2024-06-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
