# Generated by Django 5.0.6 on 2024-06-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
